rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

logger.app.name = guru.learningjournal.spark.examples
logger.app.level = info
logger.app.additivity = false
logger.app.appenderRef.console.ref = console

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.spark.name = org.apache.spark
logger.spark.level = warn
